import { Provider } from "@/components/professionals/ProviderCard";

export const CATEGORY_ORDER: {
  key: Provider["category"];
  title: string;
}[] = [
  { key: "agent", title: "Agents immobiliers" },
  { key: "property_manager", title: "Gestionnaires de biens" },
  { key: "agency", title: "Agences immobilières" },
  { key: "hotel_booking", title: "Réservation – Hôtels" },
  { key: "short_stay", title: "Réservation – Séjours à la nuit" },
  { key: "event_space", title: "Gestion d'espaces évènementiels" },
];

export const providers: Provider[] = [
  // Agents immobiliers
  {
    id: "1",
    name: "Aminata Diallo",
    city: "Dakar",
    country: "Sénégal",
    rating: 4.9,
    reviews: 156,
    listings: 28,
    category: "agent",
    badges: ["premium", "verified"],
    tags: ["Résidentiel", "Commercial", "Conseil"],
    avatar: "https://i.pravatar.cc/150?img=15",
    cover: "https://images.unsplash.com/photo-1560448075-bb4caa6c0f11?q=80&w=1200&auto=format",
  },
  {
    id: "2",
    name: "Kwame Asante",
    city: "Accra",
    country: "Ghana",
    rating: 4.7,
    reviews: 89,
    listings: 22,
    category: "agent",
    badges: ["verified"],
    tags: ["Résidentiel", "Investissement", "Luxe"],
    avatar: "https://i.pravatar.cc/150?img=12",
    cover: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200&auto=format",
  },
  {
    id: "3",
    name: "Fatou Kone",
    city: "Bamako",
    country: "Mali",
    rating: 4.8,
    reviews: 134,
    listings: 31,
    category: "agent",
    badges: ["premium"],
    tags: ["Résidentiel", "Commercial", "Terrain"],
    avatar: "https://i.pravatar.cc/150?img=25",
    cover: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=1200&auto=format",
  },
  {
    id: "4",
    name: "Ibrahim Traore",
    city: "Ouagadougou",
    country: "Burkina Faso",
    rating: 4.6,
    reviews: 67,
    listings: 19,
    category: "agent",
    badges: ["verified"],
    tags: ["Résidentiel", "Location", "Conseil"],
    avatar: "https://i.pravatar.cc/150?img=33",
    cover: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1200&auto=format",
  },

  // Agences immobilières
  {
    id: "5",
    name: "Zima Realty",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    rating: 4.9,
    reviews: 67,
    listings: 34,
    category: "agency",
    badges: ["premium", "verified"],
    tags: ["Résidentiel", "Location", "Luxe"],
    avatar: "https://i.pravatar.cc/150?img=5",
    cover: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200&auto=format",
  },
  {
    id: "6",
    name: "West Africa Properties",
    city: "Lagos",
    country: "Nigeria",
    rating: 4.8,
    reviews: 234,
    listings: 89,
    category: "agency",
    badges: ["premium", "verified"],
    tags: ["Commercial", "Résidentiel", "Investissement"],
    avatar: "https://i.pravatar.cc/150?img=8",
    cover: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format",
  },
  {
    id: "7",
    name: "Sahel Immobilier",
    city: "Niamey",
    country: "Niger",
    rating: 4.5,
    reviews: 45,
    listings: 16,
    category: "agency",
    badges: ["verified"],
    tags: ["Résidentiel", "Commercial", "Terrain"],
    avatar: "https://i.pravatar.cc/150?img=18",
    cover: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200&auto=format",
  },

  // Gestionnaires de biens
  {
    id: "8",
    name: "Grace Wanjiku",
    city: "Nairobi",
    country: "Kenya",
    rating: 4.8,
    reviews: 89,
    listings: 19,
    category: "property_manager",
    badges: ["premium"],
    tags: ["Résidentiel", "Location", "Investissement"],
    avatar: "https://i.pravatar.cc/150?img=48",
    cover: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=1200&auto=format",
  },
  {
    id: "9",
    name: "Syndic Plus Dakar",
    city: "Dakar",
    country: "Sénégal",
    rating: 4.6,
    reviews: 112,
    listings: 45,
    category: "property_manager",
    badges: ["verified"],
    tags: ["Syndic", "Gestion", "Maintenance"],
    avatar: "https://i.pravatar.cc/150?img=22",
    cover: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format",
  },

  // Réservation Hôtels
  {
    id: "10",
    name: "Hotel Bookers West Africa",
    city: "Lomé",
    country: "Togo",
    rating: 4.6,
    reviews: 54,
    listings: 12,
    category: "hotel_booking",
    badges: ["verified"],
    tags: ["Hôtellerie", "Groupe", "Business"],
    avatar: "https://i.pravatar.cc/150?img=35",
    cover: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1200&auto=format",
  },
  {
    id: "11",
    name: "Hospitality Partners",
    city: "Cotonou",
    country: "Bénin",
    rating: 4.4,
    reviews: 78,
    listings: 23,
    category: "hotel_booking",
    badges: ["premium"],
    tags: ["Hôtels", "Réservation", "Tourisme"],
    avatar: "https://i.pravatar.cc/150?img=41",
    cover: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200&auto=format",
  },

  // Séjours à la nuit
  {
    id: "12",
    name: "Daily Stays Abidjan",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    rating: 4.7,
    reviews: 72,
    listings: 25,
    category: "short_stay",
    badges: ["verified"],
    tags: ["Nuitée", "Appart'hôtel", "Famille"],
    avatar: "https://i.pravatar.cc/150?img=29",
    cover: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format",
  },
  {
    id: "13",
    name: "Short Stay Lagos",
    city: "Lagos",
    country: "Nigeria",
    rating: 4.5,
    reviews: 156,
    listings: 67,
    category: "short_stay",
    badges: ["premium", "verified"],
    tags: ["Courte durée", "Business", "Famille"],
    avatar: "https://i.pravatar.cc/150?img=37",
    cover: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1200&auto=format",
  },

  // Espaces évènementiels
  {
    id: "14",
    name: "EventHub Yaoundé",
    city: "Yaoundé",
    country: "Cameroun",
    rating: 4.5,
    reviews: 31,
    listings: 7,
    category: "event_space",
    badges: ["verified"],
    tags: ["Mariages", "Séminaires", "Conférences"],
    avatar: "https://i.pravatar.cc/150?img=44",
    cover: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format",
  },
  {
    id: "15",
    name: "Prestige Events Abidjan",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    rating: 4.7,
    reviews: 89,
    listings: 15,
    category: "event_space",
    badges: ["premium"],
    tags: ["Luxe", "Mariages", "Corporate"],
    avatar: "https://i.pravatar.cc/150?img=51",
    cover: "https://images.unsplash.com/photo-1519167758481-83f29c8e8d4b?q=80&w=1200&auto=format",
  },
];