export type VehicleKind = 'rent' | 'sale' | 'vip' | 'driver';

export type Vehicle = {
  id: string;
  title: string;
  city: string;
  countryCode: string;
  price: number;
  currency: 'XOF' | 'XAF';
  premium: boolean;
  kind: VehicleKind;
  seats?: number;
  image: string;
  rating?: number;
  reviewCount?: number;
  fuel?: string;
  gearbox?: 'auto' | 'manuelle';
  description?: string;
  amenities?: string[];
  policies?: string[];
  availability?: { available: boolean; nextAvailable?: string };
  agency?: { name?: string; verified?: boolean; address?: string; phone?: string };
  driver?: { name?: string; years?: number; languages?: string[]; trips?: number };
  doors?: number;
  luggage?: number;
  insurance?: boolean;
  gps?: boolean;
  airConditioning?: boolean;
  bluetooth?: boolean;
};
